Repository acquia/drupal-recommended-project, pull requests merged in 2024-03, with the labels that each got.

#531 Add PHP 8.3 tests
  .github/workflows/orca.yml
Labels: dependencies

#532 Add Drupal 9 tests
  .github/workflows/orca.yml
Labels: dependencies

#548 Fix workflow linting package.
  .github/workflows/orca.yml
Labels: chore

#414 ACMS-1866: Include acquia/drupal-recommended-settings plugin.
  README.md
  composer.json
  composer.lock
Labels: enhancement
